/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FlipWords: typeof import('./src/components/ui/flip-words/FlipWords.vue')['default']
    GradientButton: typeof import('./src/components/ui/gradient-button/GradientButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IntroContent: typeof import('./src/components/page/IntroContent.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticFooter: typeof import('./src/components/StaticFooter.vue')['default']
    Vortex: typeof import('./src/components/ui/vortex/Vortex.vue')['default']
    WavyBackground: typeof import('./src/components/ui/wavy-background/WavyBackground.vue')['default']
  }
}
